"""MCP-style tool layer services."""

from app.services.tools.code_search import (
    CODE_SEARCH_MAX_TOP_K,
    CodeSearchDebug,
    CodeSearchError,
    CodeSearchEvidence,
    CodeSearchResult,
    code_search,
)
from app.services.tools.diff_analyzer import (
    CHANGE_TYPE_ADDED,
    CHANGE_TYPE_DELETED,
    CHANGE_TYPE_MODIFIED,
    CHANGE_TYPE_RENAMED,
    DIFF_MAX_CHARS,
    DiffAnalysis,
    DiffAnalyzerError,
    DiffFile,
    DiffHunk,
    DiffLine,
    HUNK_MAX_LINES,
    analyze_diff,
)
from app.services.tools.file_reader import (
    BLOCKED_PATH_PARTS,
    FILE_SLICE_MAX_CHARS,
    FILE_SLICE_MAX_LINES,
    SENSITIVE_FILE_PATTERNS,
    FileSliceError,
    FileSliceResult,
    read_file_slice,
)
from app.services.tools.symbol_context import (
    DEFAULT_SYMBOL_CONTEXT_NEIGHBORS,
    SYMBOL_CONTEXT_MAX_NEIGHBORS,
    SymbolContextError,
    SymbolContextNeighbor,
    SymbolContextResult,
    SymbolContextSymbol,
    get_symbol_context,
)
from app.services.tools.static_check import (
    STATIC_CHECK_DEFAULT_ALLOWED_CHECKERS,
    STATIC_CHECK_MAX_FILES,
    STATIC_CHECK_STATUS_COMPLETED,
    STATIC_CHECK_STATUS_DENIED,
    STATIC_CHECK_STATUS_DISABLED,
    StaticCheckError,
    StaticCheckResult,
    run_safe_static_check,
)

__all__ = [
    "CODE_SEARCH_MAX_TOP_K",
    "CHANGE_TYPE_ADDED",
    "CHANGE_TYPE_DELETED",
    "CHANGE_TYPE_MODIFIED",
    "CHANGE_TYPE_RENAMED",
    "CodeSearchDebug",
    "CodeSearchError",
    "CodeSearchEvidence",
    "CodeSearchResult",
    "DIFF_MAX_CHARS",
    "DiffAnalysis",
    "DiffAnalyzerError",
    "DiffFile",
    "DiffHunk",
    "DiffLine",
    "BLOCKED_PATH_PARTS",
    "DEFAULT_SYMBOL_CONTEXT_NEIGHBORS",
    "FILE_SLICE_MAX_CHARS",
    "FILE_SLICE_MAX_LINES",
    "FileSliceError",
    "FileSliceResult",
    "SENSITIVE_FILE_PATTERNS",
    "STATIC_CHECK_DEFAULT_ALLOWED_CHECKERS",
    "STATIC_CHECK_MAX_FILES",
    "STATIC_CHECK_STATUS_COMPLETED",
    "STATIC_CHECK_STATUS_DENIED",
    "STATIC_CHECK_STATUS_DISABLED",
    "SYMBOL_CONTEXT_MAX_NEIGHBORS",
    "StaticCheckError",
    "StaticCheckResult",
    "SymbolContextError",
    "SymbolContextNeighbor",
    "SymbolContextResult",
    "SymbolContextSymbol",
    "HUNK_MAX_LINES",
    "analyze_diff",
    "code_search",
    "get_symbol_context",
    "read_file_slice",
    "run_safe_static_check",
]
